### ISSUE TITLE
Backend does not store team creator in database.

### ISSUE THREAD

**Issue by sexnine** [0xEquinox/HackPNW-Site#20]
Could be a bit of an issue if it is necessary to contact the team creator for example in the case of a duplicate team name or offensive team name.

Process for doing so:
- Create Team
- Create user
- Edit team `creator` field to user's ID

**Comment by 0xEquinox** [comment]
Solved with https://github.com/0xEquinox/HackPNW-Site/commit/da92cb9ba5da14c92a955ec78ce3bfee33c600b6
